### ISSUE TITLE
Fatal error in /whois/ip

### ISSUE THREAD

**Issue by the-swank** [mobicms/mobicms-classic#1]
Fatal error: Cannot access private property Mobicms\Form\Form::$isValid in /var/www/***/modules/whois/index.php on line 27

**Comment by THE-Swank** [comment]
And /online/guests/
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ip_via_proxy' in 'field list'

/var/www/***/modules/online/includes/guests.php, line 35
